### ISSUE TITLE
Eror Failed Launch To Browser 

### ISSUE THREAD

**Issue by agusydk3** [AlenSaito1/Whatsapp-Anime-Bot#1]
![image](https://user-images.githubusercontent.com/57493908/95545939-7baffc80-0a29-11eb-8275-03977da7aa1e.png)
Error: Failed to launch the browser process!
/root/Whatsbot/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object fiy

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/Whatsbot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/root/Whatsbot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:483:12)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by AlenSaito1** [comment]
Which OS are you using?

**Comment by agusydk3** [comment]
> Which OS are you using?

ubuntu sir

**Comment by AlenSaito1** [comment]
Can you try running these?

```sh

> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo apt install ./google-chrome-stable_current_amd64.deb

```

**Comment by agusydk3** [comment]
> Can you try running these?
> 
> ```shell
> > wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> > sudo apt install ./google-chrome-stable_current_amd64.deb
> ```

not work sir :(
![image](https://user-images.githubusercontent.com/57493908/95648615-dcf7ce80-0b02-11eb-9cd4-0006a5c0eb3e.png)

**Comment by AlenSaito1** [comment]
@MhankBarBar Any idea?

**Comment by MhankBarBar** [comment]
@agusydk3 Can you tell what version of Ubuntu you are using now?

**Comment by MhankBarBar** [comment]
Install missing libs:
```bash
> sudo apt-get install libxss1
```
To find what package contains missing libs I use:
```bash
> sudo aptitude search libXss
```

Try this, maybe it helps

**Comment by agusydk3** [comment]
i'm using Ubuntu 18.04.5 LTS

**Comment by agusydk3** [comment]
> Install missing libs:
> 
> ```shell
> > sudo apt-get install libxss1
> ```
> 
> To find what package contains missing libs I use:
> 
> ```shell
> > sudo aptitude search libXss
> ```
> 
> Try this, maybe it helps

thanks this work 👍 
![image](https://user-images.githubusercontent.com/57493908/95654078-aed8b580-0b27-11eb-804b-c0e4dc7d9700.png)

**Comment by MhankBarBar** [comment]
Okay close
